version: "3.9"

services:
  emailteste:
    image: gabrieloliveirabarbosa/emailteste:latest
    container_name: emailteste-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080